---
title: "HoneyBADGER on all FTE fresh secretory cells"
output:
  html_document:
    df_print: paged
---

## Load data

```{r}
suppressPackageStartupMessages(library(SingleCellExperiment))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(HoneyBADGER))
sce <- readRDS("../../manuscript_analysis2_0629/Rds/fresh_secretory.rds")
logcounts(sce) <- log1p(calculateCPM(sce))
scater::plotTSNE(sce, colour_by = "final.clusters")
```

```{r}
scater::plotTSNE(sce, colour_by = "Patient2")
```


```{r}
table(sce$Patient2)
```

```{r}
table(sce$Patient2, sce$final.clusters)
```

```{r}
require(biomaRt) ## for gene coordinates
mart.obj <- useMart(biomart = "ENSEMBL_MART_ENSEMBL", dataset = 'hsapiens_gene_ensembl', host = "jul2015.archive.ensembl.org")
```

## 11543

```{r}
sce2 <- sce[,sce$Patient2 %in% c("11543")]
refFT  <- rowMeans(logcounts(sce2)[, sce2$final.clusters == 2])
ft <- logcounts(sce2)
keep <- (rowSums(ft > 1) > (ncol(ft)/10)) | (refFT > 0.5)
refFT <- refFT[keep]
ft <- ft[keep,]
# ft <- ft[,1:100]
rm(keep)
dim(ft)
```



```{r}
ft <- ft[,order(paste(sce2$initial.cluster))]
gexp.mats <- setGexpMats(ft, refFT, mart.obj, filter=FALSE, scale=TRUE)
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 151,zlim = c(-0.8, 0.8)) 
```

```{r}
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 51,zlim = c(-1, 1)) 
```

## 11545

```{r}
sce2 <- sce[,sce$Patient2 %in% c("11545")]
refFT  <- rowMeans(logcounts(sce)[, sce$final.clusters == 2])
ft <- logcounts(sce2)
keep <- (rowSums(ft > 1) > (ncol(ft)/10)) | (refFT > 0.5)
refFT <- refFT[keep]
ft <- ft[keep,]
# ft <- ft[,1:100]
rm(keep)
dim(ft)
```

```{r}
ft <- ft[,order(paste(sce2$initial.cluster))]
gexp.mats <- setGexpMats(ft, refFT, mart.obj, filter=FALSE, scale=TRUE)
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 201,zlim = c(-1, 1)) 
```

```{r}
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 101,zlim = c(-1, 1)) 
```


```{r}
sce2 <- sce[,sce$Patient %in% c("11545R")]
refFT  <- rowMeans(logcounts(sce)[, sce$final.clusters == 3])
ft <- logcounts(sce2)
keep <- rowSums(ft > 1) > 5 
refFT <- refFT[keep]
ft <- ft[keep,]
rm(keep)
dim(ft)
```

```{r}
ft <- ft[,order(sce2$final.clusters)]
hb <- new('HoneyBADGER', name='11543L')
hb$setGexpMats(ft, refFT, mart.obj, filter=F, scale=T, verbose=TRUE)
```

```{r, fig.width=10}
hb$plotGexpProfile() ## initial visualization
```

## 11553

```{r}
sce2 <- sce[,sce$Patient2 %in% c("11553")]
refFT  <- rowMeans(logcounts(sce)[, sce$final.clusters == 2])
ft <- logcounts(sce2)
keep <- (rowSums(ft > 1) > (ncol(ft)/10)) | (refFT > 0.5)
refFT <- refFT[keep]
ft <- ft[keep,]
# ft <- ft[,1:100]
rm(keep)
dim(ft)
```

```{r, fig.width=10}
ft <- ft[,order(paste(sce2$initial.cluster))]
gexp.mats <- setGexpMats(ft, refFT, mart.obj, filter=TRUE, scale=TRUE)
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 201,zlim = c(-1, 1)) 
```

```{r}
gexp.plot <- plotGexpProfile(gexp.mats$gexp.norm, gexp.mats$genes, window.size = 101,zlim = c(-1, 1)) 
```

## 15066

```{r}
rm(hb)
sce2 <- sce[,sce$Patient2 %in% c("15066")]
refFT  <- rowMeans(logcounts(sce)[, sce$final.clusters == 3])
ft <- logcounts(sce2)
keep <- (rowSums(ft > 1) > (ncol(ft)/10)) | (refFT > 0.5)
refFT <- refFT[keep]
ft <- ft[keep,]
rm(keep)
dim(ft)
```

```{r}
ft <- ft[,order(paste(sce2$Patient,sce2$final.clusters))]
hb <- new('HoneyBADGER', name='11543L')
hb$setGexpMats(ft, refFT, mart.obj, filter=F, scale=T, verbose=TRUE)
```

```{r}
dim(hb$gexp.sc)
```


```{r, fig.width=10}
hb$plotGexpProfile() ## initial visualization
```

## 15072

```{r}
rm(hb)
sce2 <- sce[,sce$Patient2 %in% c("15072")]
refFT  <- rowMeans(logcounts(sce)[, sce$final.clusters == 3])
ft <- logcounts(sce2)
keep <- (rowSums(ft > 1) > (ncol(ft)/10)) | (refFT > 0.5)
refFT <- refFT[keep]
ft <- ft[keep,]
rm(keep)
dim(ft)
```

```{r}
ft <- ft[,order(paste(sce2$Patient,sce2$final.clusters))]
hb <- new('HoneyBADGER', name='11543L')
hb$setGexpMats(ft, refFT, mart.obj, filter=F, scale=T, verbose=TRUE)
```

```{r, fig.width=10}
hb$plotGexpProfile() ## initial visualization
```